namespace Kymeta.Cloud.Services.EnterpriseBroker.sdk.Workflows.SalesOrder2.Model;

public record SalesforceOrderHeaderModel
{
    public IReadOnlyList<SalesforceOrderItemModel> Items { get; init; } = Array.Empty<SalesforceOrderItemModel>();
}

public record SalesforceOrderItemModel
{
    public string? Id { get; set; }
    public string? Product2Id { get; set; }
    public bool? IsDeleted { get; set; }
    public string? OrderId { get; set; }
    public string? PricebookEntryId { get; set; }
    public string? OriginalOrderItemId { get; set; }
    public double? AvailableQuantity { get; set; }
    public double? Quantity { get; set; }
    public decimal? UnitPrice { get; set; }
    public decimal? ListPrice { get; set; }
    public decimal? TotalPrice { get; set; }
    public string? ServiceDate { get; set; }
    public DateTime? EndDate { get; set; }
    public string? Description { get; set; }
    public DateTime? CreatedDate { get; set; }
    public string? CreatedById { get; set; }
    public DateTime? LastModifiedDate { get; set; }
    public string? LastModifiedById { get; set; }
    public DateTime? SystemModstamp { get; set; }
    public string? OrderItemNumber { get; set; }
    public DateTime? Actual_Ship_Date__c { get; set; }
    public DateTime? Actual_Activation_Date__c { get; set; }
    public string? NEO_Automation_Error__c { get; set; }
    public string? ProductType__c { get; set; }
    public DateTime? Factory_Commit_Date__c { get; set; }
    public double? NEO_Shipped_Quantity__c { get; set; }
    public bool? NEO_Sync_to_Oracle__c { get; set; }
    public string? NEO_Migration_ID_OI__c { get; set; }
    public string? NEO_Oracle_Back_Order_Fulfillment_Id__c { get; set; }
    public string? NEO_Oracle_Fulfillment_Id__c { get; set; }
    public bool? NEO_Fulfillable_Product__c { get; set; }
    public string? NEO_Negotiated_Monthly_Overage__c { get; set; }
    public string? NEO_Backordered_Quantity__c { get; set; }
    public string? NEO_Oracle_Tracking_Number__c { get; set; }
    public string? NEO_Order_Shipping_Terms__c { get; set; }
    public string? NEO_Oracle_Sales_Order_Line_Id__c { get; set; }
    public string? Account_Name__c { get; set; }
    public string? Blended_Disc_Amt__c { get; set; }
    public string? Blended_Discount_Amount__c { get; set; }
    public string? Case__c { get; set; }
    public string? Financing_Term__c { get; set; }
    public bool? Need_New_Provisioning_Case__c { get; set; }
    public string? NetPrice__c { get; set; }
    public string? Provisioning_Due_Date__c { get; set; }
    public string? ShippingStatus1__c { get; set; }
    public bool? Copy_of_Oracle_Set_Up_Completed__c { get; set; }
    public bool? Oracle_Set_Up_Completed__c { get; set; }
    public string? Ship_Date__c { get; set; }
    public string? StaticProductCode__c { get; set; }
    public string? Product_Family__c { get; set; }
    public string? Product_Code_2__c { get; set; }
    public string? Product_Code__c { get; set; }
    public DateTime? Delivery_Date__c { get; set; }
    public string? AssetID__c { get; set; }
    public string? NumberOfExtensionMonths__c { get; set; }
    public string? Opportunity_Type__c { get; set; }
    public string? Product_Gen__c { get; set; }
    public string? blng__AllocatedRevenueAmount__c { get; set; }
    public string? blng__Asset__c { get; set; }
    public string? blng__BillThroughDateOverride__c { get; set; }
    public string? blng__BillableUnitPrice__c { get; set; }
    public decimal? blng__BilledAmountwithouttax__c { get; set; }
    public decimal? blng__BilledTax__c { get; set; }
    public string? blng__BillingAccount__c { get; set; }
    public string? blng__BillingGLRule__c { get; set; }
    public string? blng__BillingGLTreatment__c { get; set; }
    public string? blng__BillingRule__c { get; set; }
    public string? blng__BillingTreatment__c { get; set; }
    public string? blng__CanceledBillings__c { get; set; }
    public string? blng__FinanceBookAccounting__c { get; set; }
    public string? blng__GroupId__c { get; set; }
    public string? blng__GroupQuantity__c { get; set; }
    public string? blng__GroupUnitPrice__c { get; set; }
    public string? blng__HoldBilling__c { get; set; }
    public string? blng__IncludedUsage__c { get; set; }
    public string? blng__InvoiceGroupId__c { get; set; }
    public string? blng__InvoiceGrouping__c { get; set; }
    public string? blng__InvoiceRunProcessingStatus__c { get; set; }
    public DateTime? blng__InvoiceRunStartDate__c { get; set; }
    public string? blng__InvoiceRunStatusIndex__c { get; set; }
    public string? blng__InvoiceRun__c { get; set; }
    public string? blng__LastChargeToDate__c { get; set; }
    public string? blng__LastInvoiceTargetDate__c { get; set; }
    public string? blng__LegalEntityReference__c { get; set; }
    public string? blng__LegalEntity__c { get; set; }
    public string? blng__NextBillingDate__c { get; set; }
    public string? blng__NextChargeDate__c { get; set; }
    public string? blng__OverrideBillableUnitPrice__c { get; set; }
    public string? blng__OverrideInitialRevenueEndDate__c { get; set; }
    public string? blng__OverrideInitialRevenueStartDate__c { get; set; }
    public string? blng__OverrideNextBillingDate__c { get; set; }
    public string? blng__PendingBillings__c { get; set; }
    public decimal? blng__RevenueExpectedAmount__c { get; set; }
    public decimal? blng__RevenueLiabilityAmount__c { get; set; }
    public decimal? blng__RevenueMostLikelyAmount__c { get; set; }
    public string? blng__RevenueRecognitionRule__c { get; set; }
    public string? blng__RevenueScheduleStatus__c { get; set; }
    public string? blng__TaxCity__c { get; set; }
    public string? blng__TaxCountry__c { get; set; }
    public string? blng__TaxCounty__c { get; set; }
    public string? blng__TaxErrorMessage__c { get; set; }
    public string? blng__TaxGLRule__c { get; set; }
    public string? blng__TaxGLTreatment__c { get; set; }
    public string? blng__TaxPercentageApplied__c { get; set; }
    public string? blng__TaxRule__c { get; set; }
    public string? blng__TaxState__c { get; set; }
    public string? blng__TaxStatus__c { get; set; }
    public string? blng__TaxStreet2__c { get; set; }
    public string? blng__TaxStreet__c { get; set; }
    public string? blng__TaxTreatment__c { get; set; }
    public string? blng__TaxZipCode__c { get; set; }
    public string? blng__TerminatedBillings__c { get; set; }
    public string? blng__UniqueId__c { get; set; }
    public string? blng__UsageFloorQuantity__c { get; set; }
    public decimal? blng__TotalBilling__c { get; set; }
    public DateTime? OrderPoDate__c { get; set; }
    public string? OrderStatus__c { get; set; }
    public string? AccountID_Formula__c { get; set; }
    public string? Data_Capability_OrdP__c { get; set; }
    public string? Oracle_Invoice__c { get; set; }
}

